[package]
name = "py-iirs"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"

[lib]
name = "iirs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.1", features = ["extension-module"] }
iirs = { version = "1.0.0", path = "../" }
